- platform: gree
  name: First AC
  host: <ip of your first AC>
  port: 7000
  mac: '<mac address of your first AC. NOTE: Format can be XX:XX:XX:XX:XX:XX, XX-XX-XX-XX-XX-XX or xxxxxxxxxxxx depending on your model>'
  target_temp_step: 0.5
  #encryption_key: <OPTIONAL: custom encryption key. Integration will try to get key from device if empty>
  #encryption_version: <OPTIONAL: should be set to 2 for V1.21>
  #uid: <some kind of device identifier. NOTE: for some devices this is optional>
  #temp_sensor: <entity id of the EXTERNAL temperature sensor. For example: sensor.bedroom_temperature>
  #lights: <OPTIONAL: input_boolean to switch AC lights mode on/off. For example: input_boolean.first_ac_lights>
  #xfan: <OPTIONAL: input_boolean to switch AC xfan mode on/off. For example: input_boolean.first_ac_xfan>
  #health: <OPTIONAL: input_boolean used to switch the Health option on/off of your first AC. For example: input_boolean.first_ac_health>
  #sleep: <OPTIONAL: input_boolean to switch AC sleep mode on/off. For example: input_boolean.first_ac_sleep>
  #powersave: <OPTIONAL: input_boolean to switch AC powersave mode on/off. For example: input_boolean.first_ac_powersave>
  #eightdegheat: <OPTIONAL: input_boolean used to switch 8 degree heating on/off on your first AC>
  #air: <OPTIONAL: input_boolean used to switch air/scavenging on/off on your first AC>
  #target_temp: <OPTIONAL: input_number used to set the temperature of your first AC>
  #auto_xfan: <OPTIONAL: input_boolean: this feature will always turn on xFan in cool and dry mode to avoid mold & rust created from potential water buildup in the AC>
  #auto_light: <OPTIONAL: input_boolean: this feature will always turn light on when power on and turn light light off when power off automatically>
  #horizontal_swing: <OPTIONAL: boolean (true/false); this feature will enable horizontal swing on devices that have this functionality. This feature replaces presets in the UI
  #anti_direct_blow: <OPTIONAL: input_boolean used to switch Anti Direct Blow feature on devices devices that have this functionality. Until next release, it should be set only when device   has this feature. For example: input_boolean.first_ac_anti_direct_blow>
  #light_sensor: <OPTIONAL: input_boolean this feature will enable built-in light sensor. 
  #max_online_attempts: <OPTIONAL: integer specifying number of attempts to connect to the device before it goes into the unavailable state
  #disable_available_check: <OPTIONAL: boolean (true/false): if set to true device is always available in Home Assistant, useful for automation, device never goes into an unavailable state
