esphome:
  name: esp32-2
  friendly_name: ESP32-2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "larjXlgeB+cT3k+rpYVIrQ8nEMkc8jPKRgdqn8HXjRE="

ota:
  - platform: esphome
    password: "28b9d39c9b1d150efe740acedcc595b4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-2 Fallback Hotspot"
    password: "uFpZNmih92AU"

captive_portal:
    