esphome:
  name: eps32-2
  friendly_name: EPS32-2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sfEaJTAfzEyOSI929jMR4Pl4cl9/e7tNk7AUE+eOm4Q="

ota:
  - platform: esphome
    password: "ede5c39228720aca478911fab895feff"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eps32-2 Fallback Hotspot"
    password: "ESikF1nY0eVV"

captive_portal:
    