esphome:
  name: esp32-1
  friendly_name: ESP32-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hJ5dnQ/jW72q1hURwKm5g+lqrwcQWEA4owd49Mt9sXg="

ota:
  - platform: esphome
    password: "f172a1609ea91956af6b99c328108a49"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-1 Fallback Hotspot"
    password: "xqwj90xsE5r0"

captive_portal:
    