esphome:
  name: esphome-web-efcc0f
  friendly_name: ESP8266-1
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Allow provisioning Wi-Fi via serial
improv_serial:


# To have a "next url" for improv serial
web_server:

i2c:
  sda: GPIO14
  scl: GPIO12
  scan: True
  frequency: 400kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(montserrat), Color(id(yellow)),"Hello World RED");
      it.print(0, 14, id(unbuntu),Color(id(yellow)), "Hello World GREEN");
      it.print(0, 24, id(unbuntu), Color(id(yellow)), "Hello World MIXTE");
      it.print(0, 34, id(unbuntu), Color(id(yellow)), "Hello World YELLOW");
      it.print(0, 44, id(unbuntu), Color(id(yellow)), "Hello World YELLOW");
      it.print(0, 54, id(unbuntu), Color(id(yellow)), "Hello World YELLOW");
    rotation: 0
font:
  - file: "fonts/montserrat/Montserrat-Medium.otf"
    id: montserrat
    size: 16
  - file: "fonts/unbuntu/UbuntuMono-Regular.ttf"
    id: unbuntu
    size: 12
color:
  - id: red
    red: 100%
    green: 0%
    blue: 0%
  - id: blue
    red: 0%
    green: 0%
    blue: 100%
  - id: green
    red: 0%
    green: 100%
    blue: 0%
  - id: yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: mixt
    red: 0%
    green: 0%
    blue: 50%